#개발 마치고 체크, 재시작 정책 설정
services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: group-pm
    env_file:
      - .env
    networks:
      - group-pm-net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL 인증서 볼륨
      #- /etc/letsencrypt:/etc/letsencrypt:ro
      #- /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    # 443 → HTTPS 서비스
    #  80 → 보통 HTTPS 리다이렉트용
    depends_on:
      - app
    networks:
      - group-pm-net
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - group-pm-net

networks:
  group-pm-net:
    driver: bridge