Fserver:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  message:
    encoding: UTF-8

logging:
  level:
    root: INFO

firebase:
  service-account-path: /app/config/gpm-service-account.json