# HTTPS 서버 (메인)
server {
    listen 443 ssl http2;
    server_name goo3oo.online www.goo3oo.online;

    # SSL 설정
    ssl_certificate     /etc/letsencrypt/live/goo3oo.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/goo3oo.online/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

     # 헬스체크 엔드포인트
     #location /health {
     #   proxy_pass http://app_backend/actuator/health;
     #   access_log off;
    #}

    # 메인 애플리케이션
    location / {
        proxy_pass http://app_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# IP용 HTTP 서버 (리다이렉트 없음)
server {
    listen 80;
    server_name 52.78.204.90;

    location / {
        proxy_pass http://group-pm:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 도메인용 HTTP to HTTPS 리다이렉트
server {
    listen 80;
    server_name goo3oo.online www.goo3oo.online;
    return 301 https://$host$request_uri;
}