# HTTP → HTTPS 리다이렉트
server {
    listen 80;
    server_name goo3oo.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# IP 접속용 HTTP
server {
    listen 80;
    server_name 43.203.27.207;

    location / {
        proxy_pass http://group-pm:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# HTTPS 서버
server {
    listen 443 ssl http2;
    server_name goo3oo.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/goo3oo.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/goo3oo.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://group-pm:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
    }
}